In [1]:
import numpy
import pandas as pd

In [2]:
data = pd.read_csv('Testing.csv')

In [3]:
pos = ['OT','OL','OG','C']
training_data = data[data['Pos'].isin(pos)]

In [4]:
training_data = training_data.drop(['Player', 'School','College','Ht'], axis=1)

cond = training_data['Drafted'].isnull()
training_data.loc[cond,'Drafted'] = 'Not Drafted'
cond = training_data['Drafted'] != 'Not Drafted'
training_data.loc[cond,'Drafted'] = 'Drafted'
training_data.describe()

,Wt,40yd,Vertical,Bench,Broad Jump,3Cone,Shuttle
count,227.000000,175.000000,176.000000,179.000000,174.000000,153.000000,156.000000
mean,310.414097,5.215943,28.500000,24.871508,105.689655,7.788235,4.762179
std,16.493103,0.189467,3.234634,5.559709,6.961181,0.309237,0.194775
min,194.000000,4.520000,19.500000,11.000000,82.000000,6.770000,4.300000
25%,306.000000,5.095000,26.000000,21.000000,102.000000,7.610000,4.630000
50%,310.000000,5.220000,28.500000,25.000000,105.000000,7.770000,4.760000
75%,317.000000,5.325000,30.500000,28.000000,110.000000,8.000000,4.872500
max,364.000000,5.850000,38.000000,44.000000,124.000000,8.820000,5.380000

In [5]:
from scipy.stats import ttest_ind

drafted = training_data.query('Drafted == "Drafted"')['Bench']
not_drafted = training_data.query('Drafted == "Not Drafted"')['Bench']

training_data = training_data.dropna()
training_data.groupby('Drafted').describe()

               Wt                                                              \
            count        mean        std    min     25%    50%     75%    max
Drafted
Drafted      76.0  311.328947   9.615804  296.0  306.00  309.0  315.00  350.0
Not Drafted  48.0  309.145833  13.871737  238.0  304.75  310.0  316.25  338.0

             40yd            ...   3Cone       Shuttle                      \
            count      mean  ...     75%   max   count      mean       std
Drafted                      ...
Drafted      76.0  5.167237  ...  7.8925  8.41    76.0  4.726316  0.185342
Not Drafted  48.0  5.294167  ...  8.0700  8.82    48.0  4.847292  0.192340


              min     25%   50%     75%   max
Drafted
Drafted      4.39  4.5975  4.70  4.8600  5.38
Not Drafted  4.53  4.6975  4.83  4.9425  5.38

[2 rows x 56 columns]