In [1]:
import numpy
import pandas as pd

In [2]:
data = pd.read_csv('data_mining_project/Testing(2018-2021).csv')

In [3]:
training_data = data.drop(['Player', 'School','Ht'], axis=1)

cond = training_data['Draft_Pick'] == -1
training_data.loc[cond,'Draft_Pick'] = 'Not Drafted'
cond = training_data['Draft_Pick'] != 'Not Drafted'
training_data.loc[cond,'Draft_Pick'] = 'Drafted'
training_data.head()

  Pos     Wt  40yd  Vertical  Bench  Broad_Jump  3Cone  Shuttle   Draft_Pick
0   C  298.0  5.34      26.5   27.0        99.0   7.81     4.71      Drafted
1  OT  307.0   NaN       NaN    NaN         NaN    NaN      NaN  Not Drafted
2  OT  345.0  5.85      19.5   14.0        82.0   7.87     5.38      Drafted
3  OT  305.0  5.39      26.5   24.0        97.0   8.04     4.84      Drafted
4  OT  298.0  5.33       NaN   19.0         NaN    NaN      NaN      Drafted

In [4]:
from scipy.stats import ttest_ind

drafted = training_data.query('Draft_Pick == "Drafted"')['Bench']
not_drafted = training_data.query('Draft_Pick == "Not Drafted"')['Bench']

training_data = training_data.dropna()
training_data.groupby('Draft_Pick').describe()

               Wt                                                              \
            count        mean        std    min     25%    50%     75%    max
Draft_Pick
Drafted      76.0  311.328947   9.615804  296.0  306.00  309.0  315.00  350.0
Not Drafted  48.0  309.145833  13.871737  238.0  304.75  310.0  316.25  338.0

             40yd            ...   3Cone       Shuttle                      \
            count      mean  ...     75%   max   count      mean       std
Draft_Pick                   ...
Drafted      76.0  5.167237  ...  7.8925  8.41    76.0  4.726316  0.185342
Not Drafted  48.0  5.294167  ...  8.0700  8.82    48.0  4.847292  0.192340


              min     25%   50%     75%   max
Draft_Pick
Drafted      4.39  4.5975  4.70  4.8600  5.38
Not Drafted  4.53  4.6975  4.83  4.9425  5.38

[2 rows x 56 columns]

In [5]:
import matplotlib.pyplot as plt